/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restuarant;

import java.sql.*;

import javax.swing.JOptionPane;


public class Records extends javax.swing.JFrame {

    
    
    Connection con;
Statement stmt;
ResultSet rs;
int curRow = 0;
    
    
    
    
    public Records() {
        initComponents();
        DoConnect();
    }

public void DoConnect( ) {
try {
String host = "jdbc:derby://localhost:1527/Restaurant";
    String uName = "abu";
String uPass= "abu";
  con = DriverManager.getConnection( host, uName, uPass );
   stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );
   String SQL = "SELECT * FROM Restaurant";
   rs = stmt.executeQuery( SQL );
   
  rs.next( );
      int id_col = rs.getInt("ID");
      String id = Integer.toString( id_col );
String first_name = rs.getString("Name");
String address = rs.getString("Address");
String number = rs.getString("Number");

rs.next( );
      int id_col2 = rs.getInt("ID");
      String id2 = Integer.toString( id_col2 );
String first_name2 = rs.getString("Name");
String address2 = rs.getString("Address");
String number2 = rs.getString("Number");

rs.next( );
      int id_col3 = rs.getInt("ID");
      String id3 = Integer.toString( id_col3 );
String first_name3 = rs.getString("Name");
String address3 = rs.getString("Address");
String number3 = rs.getString("Number");

rs.next( );
      int id_col4 = rs.getInt("ID");
      String id4 = Integer.toString( id_col4 );
String first_name4 = rs.getString("Name");
String address4 = rs.getString("Address");
String number4  = rs.getString("Number");

rs.next( );
      int id_col5 = rs.getInt("ID");
      String id5 = Integer.toString( id_col5 );
String first_name5 = rs.getString("Name");
String address5 = rs.getString("Address");
String number5 = rs.getString("Number");


textID.setText(id);
textName.setText(first_name);
textAddress.setText(address);
  textNumber.setText(number);

  textID2.setText(id2);
textName2.setText(first_name2);
textAddress2.setText(address2);
  textNumber2.setText(number2);
  
  textID3.setText(id3);
textName3.setText(first_name3);
textAddress3.setText(address3);
  textNumber3.setText(number3);

  textID4.setText(id4);
textName4.setText(first_name4);
textAddress4.setText(address4);
  textNumber4.setText(number4);
  
  textID5.setText(id5);
textName5.setText(first_name5);
textAddress5.setText(address5);
  textNumber5.setText(number5);
 
}
catch ( SQLException err ) {
JOptionPane.showMessageDialog(this, err.getMessage());
}  





}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textName = new javax.swing.JTextField();
        textID = new javax.swing.JTextField();
        textNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlblAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAddress = new javax.swing.JTextArea();
        textID2 = new javax.swing.JTextField();
        textName2 = new javax.swing.JTextField();
        textNumber2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAddress2 = new javax.swing.JTextArea();
        textID3 = new javax.swing.JTextField();
        textID4 = new javax.swing.JTextField();
        textID5 = new javax.swing.JTextField();
        textName3 = new javax.swing.JTextField();
        textName4 = new javax.swing.JTextField();
        textName5 = new javax.swing.JTextField();
        textNumber3 = new javax.swing.JTextField();
        textNumber4 = new javax.swing.JTextField();
        textNumber5 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAddress3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAddress4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAddress5 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnNewRecord = new javax.swing.JButton();
        btnSaveRecord = new javax.swing.JButton();
        btnUpdateRecord = new javax.swing.JButton();
        btnDeleteRecord = new javax.swing.JButton();
        btnCancelNewRecord = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnFirst1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        textID.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        textNumber.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumberActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Number");

        jlblAddress.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jlblAddress.setText("Address");

        textAddress.setColumns(20);
        textAddress.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        textAddress.setRows(5);
        jScrollPane1.setViewportView(textAddress);

        textID2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textID2ActionPerformed(evt);
            }
        });

        textName2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        textNumber2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumber2ActionPerformed(evt);
            }
        });

        textAddress2.setColumns(20);
        textAddress2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        textAddress2.setRows(5);
        jScrollPane2.setViewportView(textAddress2);

        textID3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textID3ActionPerformed(evt);
            }
        });

        textID4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textID4ActionPerformed(evt);
            }
        });

        textID5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        textName3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        textName4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        textName5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        textNumber3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumber3ActionPerformed(evt);
            }
        });

        textNumber4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumber4ActionPerformed(evt);
            }
        });

        textNumber5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumber5ActionPerformed(evt);
            }
        });

        textAddress3.setColumns(20);
        textAddress3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        textAddress3.setRows(5);
        jScrollPane3.setViewportView(textAddress3);

        textAddress4.setColumns(20);
        textAddress4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        textAddress4.setRows(5);
        jScrollPane4.setViewportView(textAddress4);

        textAddress5.setColumns(20);
        textAddress5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        textAddress5.setRows(5);
        jScrollPane5.setViewportView(textAddress5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addGap(164, 164, 164)
                .addComponent(jLabel2)
                .addGap(472, 472, 472)
                .addComponent(jLabel3)
                .addGap(238, 238, 238)
                .addComponent(jlblAddress)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textID4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(textID)
                    .addComponent(textID2)
                    .addComponent(textID3)
                    .addComponent(textID5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textName4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textName5, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textName2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textName3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1265, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jlblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textID4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textID5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textName5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNewRecord.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnNewRecord.setText("New Record");
        btnNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRecordActionPerformed(evt);
            }
        });

        btnSaveRecord.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnSaveRecord.setText("Save Record");
        btnSaveRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRecordActionPerformed(evt);
            }
        });

        btnUpdateRecord.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnUpdateRecord.setText("Update Record");
        btnUpdateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRecordActionPerformed(evt);
            }
        });

        btnDeleteRecord.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnDeleteRecord.setText("Delete Record");
        btnDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRecordActionPerformed(evt);
            }
        });

        btnCancelNewRecord.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnCancelNewRecord.setText("Cancel New Record");
        btnCancelNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNewRecordActionPerformed(evt);
            }
        });

        btnLast.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnFirst.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFirst)
                .addGap(109, 109, 109)
                .addComponent(btnPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addGap(102, 102, 102)
                .addComponent(btnLast)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLast)
                    .addComponent(btnFirst)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addGap(30, 30, 30))
        );

        btnFirst1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnFirst1.setText("Back To Management Systems");
        btnFirst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirst1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnSaveRecord)
                .addGap(45, 45, 45)
                .addComponent(btnNewRecord)
                .addGap(44, 44, 44)
                .addComponent(btnUpdateRecord)
                .addGap(33, 33, 33)
                .addComponent(btnDeleteRecord)
                .addGap(35, 35, 35)
                .addComponent(btnCancelNewRecord)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnFirst1)
                        .addGap(339, 339, 339))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewRecord)
                    .addComponent(btnUpdateRecord)
                    .addComponent(btnSaveRecord)
                    .addComponent(btnDeleteRecord)
                    .addComponent(btnCancelNewRecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnFirst1)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1483, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRecordActionPerformed
textID.setVisible(false);   
textName.setVisible(false);  
textNumber.setVisible(false);  
textAddress.setVisible(false);  

textID3.setText(null);  
textName3.setText(null);  
textNumber3.setText(null);  
textAddress3.setText(null);  

textID2.setVisible(false);   
textName2.setVisible(false);  
textNumber2.setVisible(false);  
textAddress2.setVisible(false);  

textID4.setVisible(false);   
textName4.setVisible(false);  
textNumber4.setVisible(false);  
textAddress4.setVisible(false);  

textID5.setVisible(false);   
textName5.setVisible(false);  
textNumber5.setVisible(false);  
textAddress5.setVisible(false);  
    }//GEN-LAST:event_btnNewRecordActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
       try {
rs.first();
int id_col = rs.getInt("ID");
String id = Integer.toString(id_col);
String first_name = rs.getString("Name");
String address = rs.getString("Address");
String number = rs.getString("Number");

textID.setText(id);
textName.setText(first_name);
textAddress.setText(address);
textNumber.setText(number);

rs.next();
int id_col2 = rs.getInt("ID");
String id2 = Integer.toString(id_col2);
String first_name2 = rs.getString("Name");
String address2 = rs.getString("Address");
String number2 = rs.getString("Number");

textID2.setText(id2);
textName2.setText(first_name2);
textAddress2.setText(address2);
textNumber2.setText(number2);

rs.next();
int id_col3 = rs.getInt("ID");
String id3 = Integer.toString(id_col3);
String first_name3 = rs.getString("Name");
String address3 = rs.getString("Address");
String number3 = rs.getString("Number");

textID3.setText(id3);
textName3.setText(first_name3);
textAddress3.setText(address3);
textNumber3.setText(number3);

rs.next();
int id_col4 = rs.getInt("ID");
String id4= Integer.toString(id_col4);
String first_name4= rs.getString("Name");
String address4 = rs.getString("Address");
String number4 = rs.getString("Number");

textID4.setText(id4);
textName4.setText(first_name4);
textAddress4.setText(address4);
textNumber4.setText(number4);

rs.next();
int id_col5 = rs.getInt("ID");
String id5 = Integer.toString(id_col5);
String first_name5 = rs.getString("Name");
String address5 = rs.getString("Address");
String number5 = rs.getString("Number");

textID5.setText(id5);
textName5.setText(first_name5);
textAddress5.setText(address5);
textNumber5.setText(number5);
}
catch (SQLException err) {
JOptionPane.showMessageDialog(Records.this, err.getMessage());
}          
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
   try {
rs.next();

   textID.setText(null);
textName.setText(null);
textAddress.setText(null);
  textNumber.setText(null);

  textID2.setText(null);
textName2.setText(null);
textAddress2.setText(null);
  textNumber2.setText(null);
  
  textID3.setText(null);
textName3.setText(null);
textAddress3.setText(null);
  textNumber3.setText(null);

  textID4.setText(null);
textName4.setText(null);
textAddress4.setText(null);
  textNumber4.setText(null);
  
  textID5.setText(null);
textName5.setText(null);
textAddress5.setText(null);
  textNumber5.setText(null); 
    int id_col = rs.getInt("ID");
String id = Integer.toString(id_col);
String first_name = rs.getString("Name");
String address = rs.getString("Address");
String number = rs.getString("Number");


rs.next( );
      int id_col2 = rs.getInt("ID");
      String id2 = Integer.toString( id_col2 );
String first_name2 = rs.getString("Name");
String address2 = rs.getString("Address");
String number2 = rs.getString("Number");

rs.next( );
      int id_col3 = rs.getInt("ID");
      String id3 = Integer.toString( id_col3 );
String first_name3 = rs.getString("Name");
String address3 = rs.getString("Address");
String number3 = rs.getString("Number");

rs.next( );
      int id_col4 = rs.getInt("ID");
      String id4 = Integer.toString( id_col4 );
String first_name4 = rs.getString("Name");
String address4 = rs.getString("Address");
String number4 = rs.getString("Number");

rs.next( );
      int id_col5 = rs.getInt("ID");
      String id5 = Integer.toString( id_col5 );
String first_name5 = rs.getString("Name");
String address5 = rs.getString("Address");
String number5 = rs.getString("Number");

textID.setText(id);
textName.setText(first_name);
textAddress.setText(address);
textNumber.setText(number);
textID2.setText(id2);
textName2.setText(first_name2);
textAddress2.setText(address2);
textNumber2.setText(number2);
textID3.setText(id3);
textName3.setText(first_name3);
textAddress3.setText(address3);
textNumber3.setText(number3);
textID4.setText(id4);
textName4.setText(first_name4);
textAddress4.setText(address4);
textNumber4.setText(number4);
textID5.setText(id5);
textName5.setText(first_name5);
textAddress5.setText(address5);
textNumber5.setText(number5);


}
catch (SQLException err) {
JOptionPane.showMessageDialog(Records.this, err.getMessage());
}        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSaveRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRecordActionPerformed
       String first = textName3.getText();
         String address = textAddress3.getText();
          String job = textNumber3.getText();
           String ID = textID3.getText();
           
           int newID = Integer.parseInt(ID);
           
           try {
           rs.moveToInsertRow();
           
           rs.updateInt("ID", newID);
           rs.updateString("Name", first);
           rs.updateString("Address", address);
           rs.updateString("Number", job);
           
           rs.insertRow();
           
           stmt.close();
           rs.close();
           
            stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );
            
            String SQL = "SELECT * FROM Restaurant";
            rs = stmt.executeQuery(SQL);
            
            rs.previous();
            
            int id_col = rs.getInt("ID");
      String id2 = Integer.toString( id_col );
String first2 = rs.getString("Name");
String address2 = rs.getString("Address");
String job2 = rs.getString("Number");

textID3.setText(id2);  
textName.setText(first2);  
textAddress.setText(address2); 
textNumber.setText(job2); 

btnFirst.setEnabled( true );
btnNext.setEnabled( true );
btnLast.setEnabled( true );
btnUpdateRecord.setEnabled( true );
btnDeleteRecord.setEnabled( true );
btnNewRecord.setEnabled( true );

btnSaveRecord.setEnabled( true );
btnCancelNewRecord.setEnabled( true );
JOptionPane.showMessageDialog(this, "Record Saved");

textID.setVisible(true);   
textName.setVisible(true);  
textNumber.setVisible(true);  
textAddress.setVisible(true);  

textID2.setVisible(true);   
textName2.setVisible(true);  
textNumber2.setVisible(true);  
textAddress2.setVisible(true);  

textID4.setVisible(true);   
textName4.setVisible(true);  
textNumber4.setVisible(true);  
textAddress4.setVisible(true);  

textID5.setVisible(true);   
textName5.setVisible(true);  
textNumber5.setVisible(true);  
textAddress5.setVisible(true);  
           
           }
           catch(SQLException err){
               JOptionPane.showMessageDialog(this, err);
           }
    }//GEN-LAST:event_btnSaveRecordActionPerformed

    private void btnCancelNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNewRecordActionPerformed
       btnFirst.setEnabled( true );
btnNext.setEnabled( true );
btnLast.setEnabled( true );
btnUpdateRecord.setEnabled( true );
btnDeleteRecord.setEnabled( true );
btnNewRecord.setEnabled( true );

btnSaveRecord.setEnabled( true );
btnCancelNewRecord.setEnabled( true );
    }//GEN-LAST:event_btnCancelNewRecordActionPerformed

    private void btnDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRecordActionPerformed
        try{
        
            rs.deleteRow();
            
            stmt.close();
            rs.close();
            
            stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );
            
            String SQL = "SELECT * FROM Restaurant";
            rs = stmt.executeQuery(SQL);
            
            rs.next();
            
            int id_col = rs.getInt("ID");
      String id = Integer.toString( id_col );
String first_name = rs.getString("Name");
String address = rs.getString("Address");
String job = rs.getString("Number");


textID.setText(id);
textName.setText(first_name);
textAddress.setText(address);
  textNumber.setText(job);
            
                JOptionPane.showMessageDialog(this, "Record Deleted");
        }
        catch(SQLException err){
               JOptionPane.showMessageDialog(this, err);
           }
    }//GEN-LAST:event_btnDeleteRecordActionPerformed

    private void btnUpdateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRecordActionPerformed
       String first = textName.getText( );
String address = textAddress.getText();
String job = textNumber.getText( );
String ID = textID.getText( );

String first2 = textName2.getText( );
String address2 = textAddress2.getText();
String job2 = textNumber2.getText( );
String ID2 = textID2.getText( );

 String first3 = textName3.getText( );
String address3 = textAddress3.getText();
String job3 = textNumber3.getText( );
String ID3 = textID3.getText( );

 String first4 = textName4.getText( );
String address4 = textAddress4.getText();
String job4 = textNumber4.getText( );
String ID4 = textID4.getText( );

 String first5 = textName5.getText( );
String address5 = textAddress5.getText();
String job5 = textNumber5.getText( );
String ID5 = textID5.getText( );

int newID = Integer.parseInt( ID );
int newID2 = Integer.parseInt( ID2 );
int newID3 = Integer.parseInt( ID3 );
int newID4 = Integer.parseInt( ID4 );
int newID5 = Integer.parseInt( ID5 );

try {
rs.updateInt( "ID", newID );
rs.updateString( "Name", first );
rs.updateString("Address", address);
rs.updateString( "Number", job );
rs.updateRow( );

rs.updateInt( "ID", newID2 );
rs.updateString( "Name", first2 );
rs.updateString("Address", address2);
rs.updateString( "Number", job2 );
rs.updateRow( );

rs.updateInt( "ID", newID3 );
rs.updateString( "Name", first3 );
rs.updateString("Address", address3);
rs.updateString( "Number", job3 );
rs.updateRow( );

rs.updateInt( "ID", newID4 );
rs.updateString( "Name", first4 );
rs.updateString("Address", address4);
rs.updateString( "Number", job4 );
rs.updateRow( );

rs.updateInt( "ID", newID5 );
rs.updateString( "Name", first5 );
rs.updateString("Address", address5);
rs.updateString( "Number", job5 );
rs.updateRow( );

JOptionPane.showMessageDialog(Records.this, "Updated");
}
catch (SQLException err) {
JOptionPane.showMessageDialog(this, err);
}
    }//GEN-LAST:event_btnUpdateRecordActionPerformed

    private void btnFirst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirst1ActionPerformed
        Restuarant rs = new Restuarant();
        rs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFirst1ActionPerformed

    private void textNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumberActionPerformed

    private void textNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumber2ActionPerformed

    private void textID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textID2ActionPerformed

    private void textID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textID3ActionPerformed

    private void textID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textID4ActionPerformed

    private void textNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumber3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumber3ActionPerformed

    private void textNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumber4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumber4ActionPerformed

    private void textNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumber5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumber5ActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try {
            rs.last();
            int id_col5 = rs.getInt("ID");
            String id5 = Integer.toString(id_col5);
            String first_name5 = rs.getString("Name");
            String address5 = rs.getString("Address");
            String number5 = rs.getString("Number");

            textID5.setText(id5);
            textName5.setText(first_name5);
            textAddress5.setText(address5);
            textNumber5.setText(number5);
            
            rs.previous();
            int id_col4 = rs.getInt("ID");
            String id4 = Integer.toString(id_col4);
            String first_name4 = rs.getString("Name");
            String address4 = rs.getString("Address");
            String number4 = rs.getString("Number");

            textID4.setText(id4);
            textName4.setText(first_name4);
            textAddress4.setText(address4);
            textNumber4.setText(number4);
            
            rs.previous();
            int id_col3 = rs.getInt("ID");
            String id3 = Integer.toString(id_col3);
            String first_name3 = rs.getString("Name");
            String address3 = rs.getString("Address");
            String number3 = rs.getString("Number");

            textID3.setText(id3);
            textName3.setText(first_name3);
            textAddress3.setText(address3);
            textNumber3.setText(number3);
            
            rs.previous();
            int id_col2 = rs.getInt("ID");
            String id2 = Integer.toString(id_col2);
            String first_name2 = rs.getString("Name");
            String address2 = rs.getString("Address");
            String number2 = rs.getString("Number");

            textID2.setText(id2);
            textName2.setText(first_name2);
            textAddress2.setText(address2);
            textNumber2.setText(number2);
            
            rs.previous();
            int id_col = rs.getInt("ID");
            String id = Integer.toString(id_col);
            String first_name = rs.getString("Name");
            String address = rs.getString("Address");
            String number = rs.getString("Number");

            textID.setText(id);
            textName.setText(first_name);
            textAddress.setText(address);
            textNumber.setText(number);

        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(Records.this, err.getMessage());
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
      try {
            textID.setText(null);
          textID2.setText(null);
          textID3.setText(null);
          textID4.setText(null);
          textID5.setText(null);
          
          textName.setText(null);
          textName2.setText(null);
          textName3.setText(null);
          textName4.setText(null);
          textName5.setText(null);

         textNumber.setText(null);
         textNumber2.setText(null);
         textNumber3.setText(null);
         textNumber4.setText(null);
         textNumber5.setText(null);
                    
textAddress.setText(null);
textAddress2.setText(null);
textAddress3.setText(null);
textAddress4.setText(null);
textAddress5.setText(null);

          
            rs.previous();
        
            rs.previous();
           
            
            rs.previous();
            

            
            rs.previous();
        
            rs.previous();
            int id_col = rs.getInt("ID");
            String id = Integer.toString(id_col);
            String first_name = rs.getString("Name");
            String address = rs.getString("Address");
            String number = rs.getString("Number");

            textID5.setText(id);
            textName5.setText(first_name);
            textAddress5.setText(address);
            textNumber5.setText(number);
            
            rs.previous();
            int id_col2 = rs.getInt("ID");
            String id2 = Integer.toString(id_col2);
            String first_name2 = rs.getString("Name");
            String address2 = rs.getString("Address");
            String number2 = rs.getString("Number");

            textID4.setText(id2);
            textName4.setText(first_name2);
            textAddress4.setText(address2);
            textNumber4.setText(number2);
            
            rs.previous();
            int id_col3 = rs.getInt("ID");
            String id3 = Integer.toString(id_col3);
            String first_name3 = rs.getString("Name");
            String address3 = rs.getString("Address");
            String number3 = rs.getString("Number");

            textID3.setText(id3);
            textName3.setText(first_name3);
            textAddress3.setText(address3);
            textNumber3.setText(number3);
            
            rs.previous();
            int id_col4 = rs.getInt("ID");
            String id4 = Integer.toString(id_col4);
            String first_name4 = rs.getString("Name");
            String address4 = rs.getString("Address");
            String number4 = rs.getString("Number");

            textID2.setText(id4);
            textName2.setText(first_name4);
            textAddress2.setText(address4);
            textNumber2.setText(number4);
            
            rs.previous();
            int id_col5 = rs.getInt("ID");
            String id5 = Integer.toString(id_col5);
            String first_name5= rs.getString("Name");
            String address5 = rs.getString("Address");
            String number5 = rs.getString("Number");

            textID.setText(id5);
            textName.setText(first_name5);
            textAddress.setText(address5);
            textNumber.setText(number5);

        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(Records.this, err.getMessage());
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Records().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelNewRecord;
    private javax.swing.JButton btnDeleteRecord;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnFirst1;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNewRecord;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSaveRecord;
    private javax.swing.JButton btnUpdateRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel jlblAddress;
    private javax.swing.JTextArea textAddress;
    private javax.swing.JTextArea textAddress2;
    private javax.swing.JTextArea textAddress3;
    private javax.swing.JTextArea textAddress4;
    private javax.swing.JTextArea textAddress5;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textID2;
    private javax.swing.JTextField textID3;
    private javax.swing.JTextField textID4;
    private javax.swing.JTextField textID5;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textName2;
    private javax.swing.JTextField textName3;
    private javax.swing.JTextField textName4;
    private javax.swing.JTextField textName5;
    private javax.swing.JTextField textNumber;
    private javax.swing.JTextField textNumber2;
    private javax.swing.JTextField textNumber3;
    private javax.swing.JTextField textNumber4;
    private javax.swing.JTextField textNumber5;
    // End of variables declaration//GEN-END:variables
}
