/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WELCOME
 */
public class Main extends javax.swing.JFrame {

    public double num1;
    public double num2;
    public double num3;
    public double num4;
    public double num5;
    public double dif1;
    public double dif2;
    public double dif3;
    public double dif4;
    public double secdif1;
    public double secdif2;
    public double secdif3;
    public double thirdif1;
    public double thirdif2;
    
    public String dif1str;
    public String linrule;
    
    
    public double seqtype = 0;
    
    public double quada;
    public double quadb;
    public double quadc;
    public double term;
    
    public String plusorminus;
    
    public String plusorminusq1;
    public String plusorminusq2;
   
    public double cuba;
    public double cubb;
    public double cubc;
    public double cubd;
    
    public String plusorminusc1;
    public String plusorminusc2;
    public String plusorminusc3;
    
    
    
    
    
    public Main() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jButton1.setText("Type of Sequence");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("nTh Term");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if("".equals(jTextField1.getText()) || "".equals(jTextField2.getText()) ||
                "".equals(jTextField3.getText()) || "".equals(jTextField4.getText()) ||
                "".equals(jTextField5.getText()) ){
        jLabel1.setText("Please fill all text boxes!");
        } 
        else{
      num1= (Double.parseDouble(jTextField1.getText()));
      num2= (Double.parseDouble(jTextField2.getText()));      
      num3= (Double.parseDouble(jTextField3.getText()));      
      num4= (Double.parseDouble(jTextField4.getText()));      
      num5= (Double.parseDouble(jTextField5.getText()));
      
      dif1= num2-num1;
      dif2= num3-num2;
      dif3= num4-num3;
      dif4= num5-num4;
      
      if(dif1==dif2 && dif2==dif3 && dif3==dif4){
      seqtype = 1;
      jLabel1.setText("Linear Sequence");
      }
      else{
      secdif1 = dif2-dif1;
      secdif2 = dif3-dif2;
      secdif3 = dif4-dif3;
      
      if(secdif1 == secdif2 && secdif2 == secdif3){
      seqtype = 2;
      jLabel1.setText("Quadratic Sequence");
      }
      else{
      thirdif1= secdif2 - secdif1;
      thirdif2= secdif3 - secdif2;
      
      if(thirdif1 == thirdif2){
      seqtype = 3;
      jLabel1.setText("Cubic Sequence");
      }
      else{
      jLabel1.setText("Please input a valid sequence!");
      }
      }
      }
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jTextField1.setText(null);
       jTextField2.setText(null);
       jTextField3.setText(null);
       jTextField4.setText(null);
       jTextField5.setText(null);
       jLabel1.setText(null);
       jLabel2.setText(null);
       
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      String label = jLabel1.getText();
      if(seqtype==1){
      
     
      double linth = (num1 - dif1);
      dif1str = String.format("%.0f",dif1);
      linrule = String.format("%.0f",linth);
      
      if(linth >0){
      plusorminus = "+";     
      }
      else{
      plusorminus = "";
      }
      if(dif1 == 1){
          dif1str = "";
      }
      else{
      
      }
      
      jLabel2.setText(dif1str+"n"+plusorminus+linrule);
      }
      
      if(seqtype==2){
      quada = (secdif1/2);
      String quadastr = String.format("%.0f",quada);
      quadb = (dif1 - (3*quada));
      String quadbstr = String.format("%.0f",quadb);
      quadc = (num1 - quada - quadb);
      String quadcstr = String.format("%.0f",quadc);
      
      
     if(quadb>0){
         plusorminusq1="+";
     }
     else{
         plusorminusq1="-";
     }
     if(quadc>0){
         plusorminusq2="+";
     }
     else{
         plusorminusq2="-";
     }
    
        jLabel2.setText(quadastr + "n²" + plusorminusq1 + quadbstr + "n" + plusorminusq2 + quadcstr );
        
      }
      if(seqtype==3){
      cuba = (thirdif1/6);
      cubb = ((secdif1 - (12*cuba))/2);
      cubc = (dif1 - (7*cuba) - (3*cubb));
      cubd = (num1 - cuba - cubb - cubc);
      
      String cubastr = String.format("%.0f",cuba);
      String cubbstr = String.format("%.0f",cubb);
      String cubcstr = String.format("%.0f",cubc);
      String cubdstr = String.format("%.0f",cubd);
      
      
      term = (cuba + cubb + cubc + cubd);
      String term0 = String.format("%.0f",term);
      
      
      if(cubb>0){
      plusorminusc1 = "+";
      }
      else{
      plusorminusc1 = "";
      }
      if(cubc>0){
      plusorminusc2 = "+";
      }
      else{
      plusorminusc2 = "";
      }
      if(cubd>0){
      plusorminusc3 = "+";
      }
      else{
      plusorminusc3 = "";
      }
      jLabel2.setText(cubastr + "n³" + plusorminusc1+cubbstr+"n²"+plusorminusc2+cubcstr+"n"+plusorminusc3+cubdstr);
      }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
